-- MySQL Script generated by MySQL Workbench
-- 04/03/16 12:05:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema my_guitar_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_guitar_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_guitar_shop` DEFAULT CHARACTER SET latin1 ;
USE `my_guitar_shop` ;

-- -----------------------------------------------------
-- Table `my_guitar_shop`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`customers` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `shipping_address_id` INT(11) NULL DEFAULT NULL,
  `billing_address_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_address` (`email_address` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`addresses` (
  `address_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NOT NULL,
  `line1` VARCHAR(60) NOT NULL,
  `line2` VARCHAR(60) NULL DEFAULT NULL,
  `city` VARCHAR(40) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  `disabled` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`address_id`),
  INDEX `addresses_fk_customers` (`customer_id` ASC),
  CONSTRAINT `addresses_fk_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `my_guitar_shop`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`administrators` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`categories` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_name` (`category_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`orders` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NOT NULL,
  `order_date` DATETIME NOT NULL,
  `ship_amount` DECIMAL(10,2) NOT NULL,
  `tax_amount` DECIMAL(10,2) NOT NULL,
  `ship_date` DATETIME NULL DEFAULT NULL,
  `ship_address_id` INT(11) NOT NULL,
  `card_type` VARCHAR(50) NOT NULL,
  `card_number` CHAR(16) NOT NULL,
  `card_expires` CHAR(7) NOT NULL,
  `billing_address_id` INT(11) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `orders_fk_customers` (`customer_id` ASC),
  CONSTRAINT `orders_fk_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `my_guitar_shop`.`customers` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`order_items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `item_price` DECIMAL(10,2) NOT NULL,
  `discount_amount` DECIMAL(10,2) NOT NULL,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `items_fk_orders` (`order_id` ASC),
  INDEX `items_fk_products` (`product_id` ASC),
  CONSTRAINT `items_fk_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `my_guitar_shop`.`orders` (`order_id`),
  CONSTRAINT `items_fk_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `my_guitar_shop`.`products` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_guitar_shop`.`downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_guitar_shop`.`downloads` (
  `download_id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(45) NOT NULL,
  `date_time` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`download_id`),
  INDEX `fk_downloads_user1_idx` (`user_id` ASC),
  INDEX `fk_downloads_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_downloads_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `my_guitar_shop`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_downloads_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `my_guitar_shop`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
